config/routes.rb
Inventory::Application.routes.draw do

  resources :listitems

  resources :lists

  resources :items

  devise_for :users

  root :to => "lists#filtered"
  post "change_amount", to: "listitems#change_amount"

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Item < ActiveRecord::Base
  attr_accessible :name

  has_many :Listitems
  has_many :lists, through: :Listitems

  validates :name, presence: true
end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class List < ActiveRecord::Base
  attr_accessible :name, :user_ids, :users

  has_many :Listitems
  has_many :items, through: :Listitems

  has_and_belongs_to_many :users

  validates :name, presence: true


   
end

app/models/listitem.rb
# == Schema Information
#
# Table name: listitems
#
#  id         :integer          not null, primary key
#  amount     :integer
#  list_id    :integer
#  item_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  quota      :integer
#

class Listitem < ActiveRecord::Base
  attr_accessible :amount, :list_id, :item_id, :quota

  belongs_to :list
  belongs_to :item

  validates :list_id, presence: true
  validates :item_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  username               :string(255)
#  name                   :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible  :username, :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  attr_accessor :login
  attr_accessible :login

  has_and_belongs_to_many :lists

  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.paginate(:page => params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(params[:item])
    if @item.save
      redirect_to @item, :notice => "Successfully created item."
    else
      render :action => 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(params[:item])
      redirect_to @item, :notice  => "Successfully updated item."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_url, :notice => "Successfully destroyed item."
  end
end

app/controllers/listitems_controller.rb
class ListitemsController < ApplicationController
  def index
    @listitems = Listitem.all
  end

  def show
    @listitem = Listitem.find(params[:id])
  end

  def new
    @listitem = Listitem.new
  end

  def create
    params[:listitem].delete :item
    @listitem = Listitem.new(params[:listitem])
    if @listitem.save
      redirect_to list_path(List.find(@listitem.list_id)), :notice => "Successfully created listitem."
    else
      render :action => 'new'

    
    end
  end

  def edit
    @listitem = Listitem.find(params[:id])
  end

  def update
    @listitem = Listitem.find(params[:id])
    if @listitem.update_attributes(params[:listitem])
      redirect_to @listitem, :notice  => "Successfully updated listitem."
    else
      render :action => 'edit'
    end
  end 

  def destroy
    @listitem = Listitem.find(params[:id])
    @listitem.destroy
    redirect_to :back, :notice => "Successfully destroyed listitem."
  end

  def change_amount
    @listitem = Listitem.find(params[:id])
    #debugger
    @listitem.amount= @listitem.amount +  params[:change].to_i
    if @listitem.amount <0
      @listitem.amount = 0
    end
    @listitem.save
    redirect_to :back
  end



  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  include ApplicationHelper
  def index
    @lists = List.paginate(:page => params[:page])
  end

  def show
    @list = List.find(params[:id])
    @listitem = Listitem.new
    @listitem.list_id = @list.id
    gon.autocomplete_items = create_autocomplete_hash Item.all-@list.items

    respond_to do |format|
      format.html 
      format.js
    end
  end

  def new
    @list = List.new
    @list.users << current_user
  end

  def filtered
    @lists = List.paginate(:page => params[:page])
  end

  def create
    @list = List.new(params[:list])
    if @list.save
      redirect_to @list, :notice => "Successfully created list."
    else
      render :action => 'new'
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update_attributes(params[:list])
      redirect_to @list, :notice  => "Successfully updated list."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_url, :notice => "Successfully destroyed list."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def create_autocomplete_hash(collection)
    array = Array.new
    collection.each { |thing| array << {label: thing.name, value: thing.id} }
    return array
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/listitems_helper.rb
module ListitemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<%= form_for @item, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                items_path, :class => 'btn' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/index.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%= will_paginate @items %>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.name, item_path(item)  %></td>
        <td><%=l item.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_item_path(item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      item_path(item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_item_path,
            :class => 'btn btn-primary' %>

app/views/items/new.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @item.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Inventory</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "List Items", listitems_path  %></li>
              <li><%= link_to "Items", items_path  %></li>
              <li><%= link_to "Lists", lists_path  %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path  %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Inventory" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

  <%= render partial: 'layouts/header' %>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
            <% if flash[:alert] %>
    <p class="flash-error"><%= flash[:alert] %></p>
  <% end %>
  <% if flash[:notice] %>
    <p class="flash-notice"><%= flash[:notice] %></p>
  <% end %>
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= render partial: 'shared/gon' %>
    <%= javascript_include_tag "application" %>


  </body>
</html>

app/views/listitems/_form.html.erb
<%= semantic_form_for @listitem do |f| %>
<%= f.inputs do %>
  <% if @listitem.list_id.nil? %>
    	<%= f.input :list %>
    <% else %>
    	<%= f.input :list_id, as: :hidden %>
    <% end %>
    <% if @list.nil? %>
    <%= f.input :item %>
    <% else %>
  <%= f.input :item, as: :string, input_html: {id: "autocomplete_items", complete: "item_id"} %>
  <%= f.input :item_id , as: :hidden%>
  <% end %>
  <%= f.input :amount %>
  <%= f.input :quota %>
  <% end %>
<%= f.actions %>
<% end %>

app/views/listitems/edit.html.erb
<%- model_class = Listitem -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/listitems/index.html.erb
<%- model_class = Listitem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:list_id) %></th>
      <th><%= model_class.human_attribute_name(:item_id) %></th>
      <th><%= model_class.human_attribute_name(:quota) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @listitems.each do |listitem| %>
      <tr>
        <td><%= listitem.amount %></td>
        <td><%= List.find(listitem.list_id).name %></td>
        <td><%= Item.find(listitem.item_id).name %></td>
        <td><%= listitem.quota %></td>
        <td><%=l listitem.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_listitem_path(listitem), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      listitem_path(listitem),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_listitem_path,
            :class => 'btn btn-primary' %>

app/views/listitems/new.html.erb
<%- model_class = Listitem -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/listitems/show.html.erb
<%- model_class = Listitem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @listitem.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:list_id) %>:</strong></dt>
  <dd><%= @listitem.list_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:item_id) %>:</strong></dt>
  <dd><%= @listitem.item_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              listitems_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_listitem_path(@listitem), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              listitem_path(@listitem),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/lists/_form.html.erb
<%= semantic_form_for @list do |f| %>

  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :users, wrapper_html: {class: "hidden"} %>
    <% end %>

  <%= f.actions %>
  
<% end %>

app/views/lists/_modify_users.erb
<%= semantic_form_for @list do |f|%>
	<%= f.inputs do %>
		<%= f.input :users, as: :check_boxes%>

	<% end %>
	<%= f.actions do %>
		<%= f.action :submit %>
		<% end %>
<% end %>

app/views/lists/_show.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @list.name %></dd>
<table class="table table-bordered">
  <thead>
    <th>Name</th>
    <th>Username</th>
  </thead>
  <tbody>
<% @list.users.each do |item| %>
<tr>
  <td><%= item.name %></td>
  <td><%= item.username %></td>
</tr>
<% end %>
</tbody>
</table>
<table class="table table-bordered">
  <thead>
    <th>Name</th>
    <th>Amount</th>
    <th>Quota</th>
  </thead>
  <tbody>
<% @list.Listitems.each do |l_item| %>
<tr>
  <td><%= Item.find(l_item.item_id).name %></td>
  <td><%= l_item.amount %>     
    <%= link_to "+", change_amount_path(id: l_item.id, change: 1), class: "increment", method: :post %>
    <%= link_to "-", change_amount_path(id: l_item.id, change: -1), method: :post, class: "decrement"%>
  </td>
  <td><%= l_item.quota %>
    <%= link_to "Remove", listitem_path(l_item.id), method: :delete %></td>
  </tr>
<% end %>
</tbody>
</table>


<div class="toggle_list"><div class= "togglebutton"></div>
  Add Items to list </div> <!-- toggle -->
<div class="toggled_list", hidden='true'> 
  <%= render partial: 'listitems/form'  %>
</div>


<div class="toggle_user">
 Manage Users <div class= "togglebutton"></div>
 </div> <!-- toggle -->
<div class="toggled_user", hidden='true'> 
  <%= render partial: 'lists/modify_users' %>
</div>



</dl>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              lists_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_list_path(@list), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              list_path(@list),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/lists/edit.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lists/filtered.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%= will_paginate @lists %>
    <% @lists.each do |list| %>
      <% if list.users.include? current_user %>
      <tr>
        <td><%= link_to list.name, list_path(list), remote: true
%></td>
        <td><%=l list.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_list_path(list), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      list_path(list),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_list_path,
            :class => 'btn btn-primary' %>

app/views/lists/index.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%= will_paginate @lists %>
    <% @lists.each do |list| %>
      <% #if list.users.include? current_user %>
      <tr>
        <td><%= link_to list.name, list_path(list)%></td>
        <td><%=l list.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_list_path(list), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      list_path(list),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
      <%# end %>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_list_path,
            :class => 'btn btn-primary' %>

app/views/lists/new.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lists/show.html.erb
<%= render partial: "show" %>